version: "3"
services:
  client:
    image: webapp-client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
  api:
    image: webapp-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - "27017:27017"
    command: mongod --noauth --smallfiles
